# This is the name of the work flow
name : deploy-marketing

# Which section of the code have to be watched "on push" is being defined here.
# We need to watch master branch --> and the folder packages/container/** all it's contents.
on:
  push:
    branches:
      - master
      # We can keep as many branches as we wanted.
    paths:
      - 'packages/marketing/**'

# We are defining the defaults. This will set the execution environment inside the working-directory.
defaults:
  run:
    working-directory: packages/marketing

jobs:
  build:
    runs-on: ubuntu-latest #This runs the steps on the ubuntu server on github

    steps:
      - uses: actions/checkout@v2  #This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
      - run: npm install
      - run: npm run build

    # Now we wish to deploy all the build files to Amazon S3, there we need something called AWS CLI...cont
    # It will automatically gives access to AWS
      - uses: chrislennon/action-aws-cli@v1.1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
          
      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/marketing/latest
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/marketing/latest/MarketingRemoteEntry.js"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    # Explanation:  aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest.
    # We are trying to react to "aws s3" cli from chris lennon, trying to sync the dist folder from "npm run build" to s3 bucket.
    # Bucket is essentially a place where we can store the files.
    # Bucket name s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest.
    # The code is being pushed to Bucket --> container --> latest folder.



